theme: jekyll-theme-cayman
title: <a href="https://rocknroll87q.github.io/cerebrum7t/" target="_blank">CEREBRUM 7T</a>
description: A fast and fully-volumetric brain segmentation of out-of-the-scanner 7T MR volumes

show_downloads: [true]

github:
  zip_url: https://github.com/rockNroll87q/cerebrum7t
  another_url: https://www.biorxiv.org/content/10.1101/2020.07.07.191536v1
