theme: jekyll-theme-cayman
title: CEREBRUM 7T
description: A fast and fully-volumetric brain segmentation of out-of-the-scanner 7T MR volumes

show_downloads: [true]

github:
  zip_url: http://example.com/download.zip
  another_url: https://www.biorxiv.org/content/10.1101/2020.07.07.191536v1
